server:
  port: 8080
spring:
  datasource:
    username: root
    password: toor
    url: jdbc:mysql://localhost:3306/jss?serverTimezone=UTC
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true